# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linux',
            old_name='content_html',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='linux',
            old_name='title',
            new_name='name',
        ),
    ]
