# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='classes',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
